@session=f1b4bbcb-61b4-4fcf-af4f-e20bad13e55d
@HOST=localhost:8081


# @name login
POST /xas/ HTTP/1.1
Host: {{HOST}}
Content-Type: application/json
Cookie: SessionTimeZoneOffset=-480;

{
  "action": "login",
  "params": {
    "username": "MxAdmin",
    "password": "1"
  }
}

###


# @name retrieve
POST /xas/ HTTP/1.1
Host: {{HOST}}
Content-Type: application/json
x-csrf-token: {{login.response.body.csrftoken}}

{
  "action": "retrieve_by_ids",
  "params": {
    "ids": ["13792273858913057"],
    "schema": {}
  }
}
